name: "Terraform Destroy"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm destroying the workspace"
        required: true
        default: "NO"

env:
  TF_CLOUD_ORGANIZATION: "farouk"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "dsb-aws-devsecops-pipelines"
  CONFIG_DIRECTORY: "./terraform/pipelines"

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # only run on main AND if user typed DESTROY
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.confirm == 'DESTROY' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.1
        id: destroy-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: destroy-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.destroy-upload.outputs.configuration_version_id }}
          is_destroy: true

      - name: Apply Destroy Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        id: destroy-apply
        with:
          run: ${{ steps.destroy-run.outputs.run_id }}
          comment: "Manual Destroy Run from GitHub Actions CI ${{ github.sha }}"
